// Auto-generated by sync-testimonials — do not edit manually.
// Source: Google Sheets via Apps Script.
// Last sync: 2026-06-27T00:04:56.070Z

export interface Testimonial {
  id: string;
  name: string;
  instagramHandle?: string;
  destination: string;
  stars: number;
  nps: number;
  wouldReturn: 'si' | 'talvez' | 'no';
  text: string;
  date: string;
  featured?: boolean;
}

export interface TestimonialMetrics {
  avgStars: number;
  npsScore: number;
  wouldReturnPct: number;
  total: number;
}

export const testimonials: Testimonial[] = [
  {
    "id": "r_0",
    "name": "Constanza Camacho",
    "instagramHandle": "Coniiiiih",
    "destination": "Buzios, Brasil",
    "stars": 5,
    "nps": 10,
    "wouldReturn": "si",
    "text": "Me encantó viajar con las girlas! Fue una experiencia hermosa porque se forman grupos muy copados, buena onda y divertidos. Lo que más me gustó fue el mix entre el deporte y conectar con experiencias locales. Las coordinadoras le dan una vibra única y súper dinámica al viaje, Valu e Ina son lo más! Sin dudas lo recomendaría especialmente para mujeres que quieren viajar pero no quieren hacerlo solas. Una vez que probas un viajecito de estos no te bajas másss 😅🫶🏼💞 10/10",
    "date": "2026-06-27",
    "featured": false
  }
];

export function getMetrics(data: Testimonial[]): TestimonialMetrics {
  if (!data.length) return { avgStars: 0, npsScore: 0, wouldReturnPct: 0, total: 0 };
  const avgStars = Math.round((data.reduce((s, t) => s + t.stars, 0) / data.length) * 10) / 10;
  const promoters  = data.filter(t => t.nps >= 9).length;
  const detractors = data.filter(t => t.nps <= 6).length;
  const npsScore   = Math.round(((promoters - detractors) / data.length) * 100);
  const returning      = data.filter(t => t.wouldReturn === 'si').length;
  const wouldReturnPct = Math.round((returning / data.length) * 100);
  return { avgStars, npsScore, wouldReturnPct, total: data.length };
}

export function getFeatured(data: Testimonial[], limit = 4): Testimonial[] {
  const featured = data.filter(t => t.featured);
  return (featured.length >= limit ? featured : data).slice(0, limit);
}
