// Auto-generated by sync-testimonials — do not edit manually.
// Source: Google Sheets via Apps Script.
// Last sync: 2026-06-27T00:55:11.356Z

export interface Testimonial {
  id: string;
  name: string;
  instagramHandle?: string;
  destination: string;
  stars: number;
  nps: number;
  wouldReturn: 'si' | 'talvez' | 'no';
  text: string;
  date: string;
  featured?: boolean;
}

export interface TestimonialMetrics {
  avgStars: number;
  npsScore: number;
  wouldReturnPct: number;
  total: number;
}

export const testimonials: Testimonial[] = [
  {
    "id": "r_0",
    "name": "Constanza Camacho",
    "instagramHandle": "Coniiiiih",
    "destination": "Buzios, Brasil",
    "stars": 5,
    "nps": 10,
    "wouldReturn": "si",
    "text": "Me encantó viajar con las girlas! Fue una experiencia hermosa porque se forman grupos muy copados, buena onda y divertidos. Lo que más me gustó fue el mix entre el deporte y conectar con experiencias locales. Las coordinadoras le dan una vibra única y súper dinámica al viaje, Valu e Ina son lo más! Sin dudas lo recomendaría especialmente para mujeres que quieren viajar pero no quieren hacerlo solas. Una vez que probas un viajecito de estos no te bajas másss 😅🫶🏼💞 10/10",
    "date": "2026-06-27",
    "featured": false
  },
  {
    "id": "r_1",
    "name": "Vir ✨",
    "instagramHandle": "Virr.vegaa",
    "destination": "Buzios, Brasil",
    "stars": 5,
    "nps": 10,
    "wouldReturn": "si",
    "text": "Cada una de las experiencias con las Girlas se lleva un lugar en mi corazón por sí mismas. No solo son Valu e Ina (que son las mejores organizadoras que puedan encontrar), sino por los lugares hermosos, las anécdotas demenciales y la gente hermosa que me ha llenado la vida de risas, calma y MUCHÍSIMA LUZ!!! Con ellas me animé a hacer cosas que nunca había hecho, a conocer personas con las que quizás nunca hubiera hablado y ser yo misma a pesar del miedo, sabiendo que hay un montón de chicas que sin importar cuantas veces tropiece, siempre me van a levantar! \n\nSi estás pensando en sumarte a algún viaje, NO LO DUDES MÁS! Te juro que va a ser la mejor decisión de tu vida :)",
    "date": "2026-06-27",
    "featured": false
  },
  {
    "id": "r_2",
    "name": "Andy Linares",
    "instagramHandle": "Andyandotherthings",
    "destination": "Buzios, Brasil",
    "stars": 5,
    "nps": 9,
    "wouldReturn": "si",
    "text": "Lo que hacen Ina y Valu va muchísimo más allá de organizar un viaje.\n\nEstán creando un espacio donde mujeres que muchas veces llegan sin conocerse, con miedos o sintiendo que “eso no es para ellas”, terminan animándose a hacer cosas que jamás habrían hecho solas.\n\nNo se trata solo de surfear o de vivir una aventura. Se trata de descubrir de lo que una es capaz cuando se siente segura, acompañada y libre de cualquier juicio.\n\nHay algo muy especial en la comunidad que construyeron: una donde no hace falta demostrar nada, donde cada una puede ir a su ritmo, celebrar los logros de las demás y disfrutar el proceso.\n\nOjalá nunca pierdan de vista el impacto que tienen, porque probablemente ni ustedes mismas dimensionan la cantidad de confianza, valentía y recuerdos que están ayudando a construir en cada mujer que se anima a viajar con ustedes.\n\nGracias por crear algo tan genuino.",
    "date": "2026-06-27",
    "featured": false
  },
  {
    "id": "r_3",
    "name": "Aimé",
    "instagramHandle": "Aime.garcia",
    "destination": "Buzios, Brasil",
    "stars": 5,
    "nps": 10,
    "wouldReturn": "si",
    "text": "Lo que empezó como un viaje para conocer Buzios terminó siendo una de las mejores experiencias de mi vida.\n\nMe encontré haciendo cosas que jamás imaginé que haría, como un trekking de noche o animarme a surfear sin experiencia y con mucho miedo. Pero en todo momento me sentí acompañada, motivada y contenida por el grupo.\n\nGran parte de todo eso fue gracias a Ina y Valu. Estuvieron en cada detalle, siempre generando propuestas, experiencias, risas y momentos que ayudaron a crear un clima hermoso de compañerismo y conexión entre todas. Se nota el amor y la dedicación que ponen en el viaje.\n\nVolví con el corazón lleno, con recuerdos increíbles y con amigas que quiero seguir teniendo en mi vida. Si estás pensando en viajar con las chicas, hacelo. No es solo un viaje: es una experiencia que te transforma y te deja personas hermosas para siempre ❤️",
    "date": "2026-06-27",
    "featured": false
  },
  {
    "id": "r_4",
    "name": "Mica",
    "instagramHandle": "micaelaboveroo",
    "destination": "Buzios, Brasil",
    "stars": 5,
    "nps": 10,
    "wouldReturn": "si",
    "text": "Quisiera poder poner en palabras la felicidad que siento recordando cada momento de risa y alegría. Nos reíamos hasta que nos dolía la panza, sin importar nada más. Ojalá todas puedan vivir esa experiencia de compañerismo, alegría y disfrute dónde lo único que importaba era pasarla bien. Fue un viaje en el que no solo se aprendió un deporte nuevo sino que se aprendió a disfrutar sin que nada más importe, me hicieron olvidar de todo y nos invitaron a cada una de nosotras a estar en nuestro mejor momento, no exagero cuando digo que aún me siento muy feliz. La magia y la esencia de Ina y Valu se sintió en cada momento del viaje, nada era un simple momento ellas lo hacían ver como el momento más lindo, nos enseñaron a qué si no se disfruta hoy, cuando lo vas hacer? Nos cuidaron , se preocuparon y nos apoyaron de una manera increíble, realmente se cargaron el viaje al hombro y no dejaron que nadie se vaya sin disfrutar. Les aseguro que de la mano de ellas jamás le va a faltar aventura, diversión y sobre todo valentía. Hicieron que todas podamos encontrar un apoyo en el grupo y que podamos llevarnos buenas amigas. Ese grupo no lo cambio por nada. Ojalá pueda volver mil veces más con ustedes. Amo a mi grupete de Buzios\n Gracias por esta hermosa experiencia chicas. \nY las que aún no viajaron, les juro que no se van arrepentir nunca de decirle que si a un viaje organizado por estás mujeres.",
    "date": "2026-06-27",
    "featured": false
  }
];

export function getMetrics(data: Testimonial[]): TestimonialMetrics {
  if (!data.length) return { avgStars: 0, npsScore: 0, wouldReturnPct: 0, total: 0 };
  const avgStars = Math.round((data.reduce((s, t) => s + t.stars, 0) / data.length) * 10) / 10;
  const promoters  = data.filter(t => t.nps >= 9).length;
  const detractors = data.filter(t => t.nps <= 6).length;
  const npsScore   = Math.round(((promoters - detractors) / data.length) * 100);
  const returning      = data.filter(t => t.wouldReturn === 'si').length;
  const wouldReturnPct = Math.round((returning / data.length) * 100);
  return { avgStars, npsScore, wouldReturnPct, total: data.length };
}

export function getFeatured(data: Testimonial[], limit = 4): Testimonial[] {
  const featured = data.filter(t => t.featured);
  return (featured.length >= limit ? featured : data).slice(0, limit);
}
